package com.testehan.kotlinexperiments.basics

fun main() {

    val tv = SmartDevice("samsung", 100000)
//    tv.brand = "samsung"
//    tv.price = 100000
    println("${tv.brand}  ${tv.price/100}$")

    val phone = SmartDevice("apple", 200000)
    phone.brand = "apple"
    phone.price = 200000
    println("${phone.brand}  ${phone.price/100}$")

    val dishwasher = SmartDevice("whirlpool")
    println("${dishwasher.brand} ${dishwasher.price/100}$");

    println(dishwasher)

    var userDan = User(1, "dante")
    var userAna = User(2, "anita")

    println(userDan)
    println(userAna.toString())
    println(userAna == userDan)
    println(userAna == userAna)

}
                    // this is how you specify the constructor..as the IDE tells you, you can remove the
                    // "constructor" keyword as it is not needed
class SmartDevice (
       var brand: String?,
       var price: Int = 0
){

    constructor(brand : String) : this(brand, 0)

    // generated by IDEA from Code->Generate menu
    override fun toString(): String {
        return "SmartDevice(brand=$brand, price=$price)"
    }

    // generated by IDEA from Code->Generate menu
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is SmartDevice) return false

        if (brand != other.brand) return false
        if (price != other.price) return false

        return true
    }

    override fun hashCode(): Int {
        var result = brand?.hashCode() ?: 0
        result = 31 * result + price
        return result
    }
}


// see notes for more info on "data classes" ; at a first glance they seem to be like "records" in java
data class User(val id: Int, val name: String)

